---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: auth-serviceRole
spec:
  rules:
  - constraints:
    - key: destination.labels[app]
      values:
      - account
    methods:
    - '*'
    services:
    - '*'
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: auth-serviceRoleBinding
spec:
  roleRef:
    kind: ServiceRole
    name: auth-serviceRole
  subjects:
  - user: '*'
  - properties:
      request.regex.headers[username]: alvaro
    user: ""
